baseURL = "/"
languageCode = "en-us"
title = "Benjamin Buettner"
theme = "hugo-theme-shell"


[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Benjamin Buettner's Portfolio!"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  schema = "solarized_dark"

  
  userName = "bbenja"
  pcName = "laptop"
  workDir = "workdir"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  terminalDelay = 20

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  activityDelay = 5

  description = """
  Hi I am Benjamin Buetter.
  Ph.D. Candidate at TU/e, Netherlands.

  Nice to meet you!
 

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "contact_details"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["Github", "https://github.com/b-benja"],
    ["LinkedIn", "https://www.linkedin.com/in/benjamin-buettner"],
    ["TU/e", "https://research.tue.nl/en/persons/benjamin-b%C3%BCttner-zhang"]
  ]